doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '12'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Location:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/DomainModel/Location'
        prefix: 'App\DomainModel\Location'
        alias: Location
      Measurement:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/DomainModel/Measure'
        prefix: 'App\DomainModel\Measure'
        alias: Measure
