version: '3.5'

services:
  db:
    container_name: weather_db
    build:
      context: docker/db
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=secret12354

  nginx:
    container_name: weather_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: weather_php
    build:
      context: docker/php
    volumes:
      - .:/var/www/html:cached

  node:
    container_name: weather_node
    image: node:12
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${APP_ENV}
    command: yarn ${APP_ENV}
    volumes:
      - .:/home/node/app

  redis:
    container_name: weather_redis
    image: redis:latest
    volumes:
      - ./docker/redis:/data:cached