index:
    path: /
    controller: App\UI\Rest\Landing::index

result-coords:
    path: /coords
    controller: App\UI\Rest\Measurements::getMeasurementForCoords

result-location:
    path: /location
    controller: App\UI\Rest\Measurements::getMeasurementForLocation
